# Generated by Django 4.1.5 on 2023-02-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternatelabel',
            unique_together={('name', 'label')},
        ),
    ]
