# Generated by Django 4.1.5 on 2023-02-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='Category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.category'),
        ),
    ]
